config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get '/about' => 'pages#about' #goes to pages controller with about action
  get '/portfolio'=> 'pages#portfolio'
  get '/services'=> 'pages#services' 
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	#These actions? make sure that someone actually puts in a response for both name and e-mail.
	validates :name, presence: true
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	# This action will look in the views folder for an html file called new.html.erb.
	def new
		# This creates a new contact object and saves it on the web server.	This is a specific user object.	
		@contact = Contact.new
	end
	
	# This action will look in the views folder for an html file called create.html.erb.
	def create
		@contact = Contact.new(contact_params)

		# This ruby method saves the contact information
		# @contact.save results in true
		if @contact.save
			flash[:success] = "Message sent."
			redirect_to new_contact_path
		# @contact.save results in false
		else
			flash[:danger] = "Error occured, message has not been sent."
			redirect_to new_contact_path
		end
	end

	private
		def contact_params
			#This white lists the parameters. I have no idea what that means.
			params.require(:contact).permit(:name, :email, :comments)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about		
	end

	def portfolio
	end

	def services
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<div class="well">
			<%= form_for @contact do |f| %>
				<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: "form-control" %>
				</div>

				<div class="form-group">	
				<%= f.label :email %>
				<%= f.email_field :email, class: "form-control" %>
				</div>

				<div class="form-group">
				<%= f.label :comments %>
				<%= f.text_area :comments, class: "form-control" %>
				</div>

				<%= f.submit 'Submit', class: 'btn btn-default' %>
			<% end %>
		</div>	
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roberson Development Group</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <!-- <i class="fa fa-users"></i> -->
        Roberson Development Group
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Portfolio", portfolio_path %></li>
        <li><%= link_to "Services", services_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
<article>
<div class="container">
  <%= yield %>
</div>
</article>
<footer class="footer">
  <div class="container">
  <p class="text-muted">test</p>
  </div>
</footer>
<script>
  var h = $('.container');
</script>
</body>
</html>

app/views/pages/about.html.erb
<div class="about-welcome text-center">
	<h1>About Your Developer</h1>
</div>
<div class="about-content">
	<p><span>Joshua Roberson</span></p>
	<p>Howdy! Chances are that I have seen it all. Or at least that's what it feels like to me sometimes. I have worked in business analytics for over five years and have had the pleasure to work credit analysis in the banking industry, project feasibility in the real estate industry, and economic analysis on various levels.</p>
	<p></p>
</div>

app/views/pages/home.html.erb
<div class="index-welcome text-center">
	<h1>Welcome</h1>
</div>
<div class="index-content">
	<p>Roberson Development Group is pleased to have the opportunity to serve your software development needs. We are a small shop development team that provides a variety of solutions focused on web development and business analytic packages. We are based out of College Station, Texas right in the heart of Aggieland.</p>
	<p>We put a tremendous amount of pride and effort into every client's needs from start to finish. Our work is efficient and most important economical.</p>
</div>

app/views/pages/portfolio.html.erb
<div class="portfolio-title">
	<div class="row text-center">
	<h1>Website Portfolio Gallery</h1>
	</div>
</div>
<div class="portfolio-gallery">
	<div class="row">
		<div class="col-md-4 image-box"> 
			<div class="image-cell">
				<%= image_tag "roberson-rails-thumbnail.jpg" %>
			</div>
			<div class="image-title">
				<p>test one</p>
			</div>
		</div>
		<div class="col-md-4 image-box hide"> 
			<div class="image-cell">
				<%= image_tag "roberson-rails-thumbnail.jpg" %>
			</div>
			<div class="image-title">
				<p>test one</p>
			</div>
		</div>
		<div class="col-md-4 image-box hide"> 
			<div class="image-cell">
				<%= image_tag "roberson-rails-thumbnail.jpg" %>
			</div>
			<div class="image-title">
				<p>test one</p>
			</div>
		</div>
	</div>
	<div class="row hide">
		<div class="col-md-4 image-box"> 
			<div class="image-cell">
				<%= image_tag "roberson-rails-thumbnail.jpg" %>
			</div>
			<div class="image-title">
				<p>test one</p>
			</div>
		</div>
		<div class="col-md-4 image-box"> 
			<div class="image-cell">
				<%= image_tag "roberson-rails-thumbnail.jpg" %>
			</div>
			<div class="image-title">
				<p>test one</p>
			</div>
		</div>
		<div class="col-md-4 image-box"> 
			<div class="image-cell">
				<%= image_tag "roberson-rails-thumbnail.jpg" %>
			</div>
			<div class="image-title">
				<p>test one</p>
			</div>
		</div>
	</div>	
</div>

app/views/pages/services.html.erb
<div class="text-center">
	<h1>Services</h1>
</div>